services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - /opt/frigate/mosquitto/config:/mosquitto/config
      - /opt/frigate/mosquitto/data:/mosquitto/data
      - /opt/frigate/mosquitto/log:/mosquitto/log

  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    privileged: true
    stop_grace_period: 30s
    shm_size: "256mb"
    depends_on:
      - mosquitto
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1
    group_add:
      - "993"
      - "44"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8971:8971"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "1984:1984" # go2rtc
    environment:
      TZ: America/Chicago
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
      LIBVA_DRIVER_NAME: iHD
      FRIGATE_DISABLE_HOMEKIT: "true"
      PLUS_API_KEY: ${PLUS_API_KEY}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
